# Generated by Django 3.2.8 on 2021-10-07 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date register')),
            ],
        ),
    ]
